#!/usr/bin/env bash

################################
# Shows info about screen brightness.
# Allows simple brightness controls.
#
# By Thomas MEREL <thomas.merel.44@gmail.com>
# Base on @EliteTK sound manager for i3blocks
#
# Dependencies:
# - lux
# - calc
# - ttf-font-icons
#
# @return {Number}: Current screen luminosity
################################

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
status=0

step=5

getBrightness() {
    # get lux return
    local lux=$(lux)
    
    # get current and max
    current=$( echo $lux | cut -d';' -f2)
    ref=$(echo $lux | cut -d';' -f3)
    
    # calcul percent
    calcul=$(calc "$current*100/$ref")

    # round percent
    round=$(printf '%.0f\n' $calcul)
    
    # return result
    echo "$round"
}

# get mouse actions
case $BLOCK_BUTTON in
    #right click
    #set to 20%
    3) lux -S 21% > /dev/null ;;

	# scroll up
	# raise bright
	4) lux -a $step > /dev/null ;;

	# scroll down
	# lower bright
	5) lux -s $step >/dev/null ;;
esac

light=$(getBrightness)

# level-based icon
if [[ $light -le 20 && $light -ge 1 ]]; then
#	low bright
	icon=""
elif [[ $light -lt 1 ]]; then
#   no bright and no black screen when brightness at 0%
    lux -S 1% > /dev/null
    icon=""
elif [[ $light -ge 80 ]]; then
#	high bright
	icon=""
else
#	middle bright
	icon=""
fi

full="$icon $light%"
short=$light

echo $full
echo $short
exit $status
