#!/usr/bin/env bash

################################
# Shows info about screen brightness.
# Allows simple brightness controls.
#
# By Thomas MEREL <thomas.merel.44@gmail.com>
# Base on @EliteTK sound manager for i3blocks
#
# Dependencies:
# - xbacklight
# - lux
# - ttf-font-icons
#
# @return {Number}: Current screen luminosity
################################

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
status=0

step=5

getBrightness() {
	xbacklight
}


case $BLOCK_BUTTON in
    #right click
    #set to 20%
    3) lux -S 21% > /dev/null ;;

	# scroll up
	# raise bright
	4) lux -a $step > /dev/null ;;

	# scroll down
	# lower bright
	5) lux -s $step >/dev/null ;;
esac

light=$(getBrightness)

# level-based icon
if (( $light -le 10 )); then
#	no bright
	icon=""
elif (( $light -le 1)); then
    lux -S 1% > /dev/null
    icon=""
elif (( $light -ge 90 )); then
#	low bright
	icon=""
elif (( $light -lt 90 && $light -gt 10 )); then
#	high bright
	icon=""
fi

full="$icon ${light%.*}%"
short=$light

echo $full
echo $short
exit $status
