#!/bin/bash

case $BLOCK_BUTTON in
	# right click: show details
	# TODO: fix
	3)
		local summary=$(du -h --max-depth=1 $disk)
		notify-send "Linux > Windows"
	;;
	
esac



echo    $(uname -r | sed "s/-ARCH//")
